wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.4
    start_time: 1663458153.931597
    t:
      1:
      - 1
      - 4
      - 5
      - 53
      - 55
      2:
      - 1
      - 4
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.4
      5: 0.13.3
      8:
      - 1
      - 2
      - 5
